name: 'shopify-cart - SonarCloud Scan'
description: 'Scan shopify-cart'

runs:
  using: 'composite'
  steps:
    - name: Preview Data - npm ci
      shell: bash
      run: npm ci
      working-directory: packages/shopify-checkout
    - name: Preview Data - npm run test
      shell: bash
      run: npm run test
      working-directory: packages/shopify-checkout
    - name: Preview Data - npm run build
      shell: bash
      run: npm run build
      working-directory: packages/shopify-checkout
    - name: Preview Data - npm run test:coverage
      shell: bash
      run: npm run test:coverage
      working-directory: packages/shopify-checkout
    - name: Analyze with SonarCloud
      shell: bash
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
      with:
        projectBaseDir: packages/shopify-checkout
        args: >
          -Dsonar.organization=getnacelle
          -Dsonar.projectKey=getnacelle_nacelle-js_package_shopify_checkout
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          -Dsonar.sources=src
          -Dsonar.exclusions=src/**/*.test.ts
          -Dsonar.tests=src
          -Dsonar.test.inclusions=src/**/*.test.ts
