name: Feature Request
description: Suggest a feature or enhancement
title: '[Enhancement]: '
labels: ['enhancement', 'triage']
body:
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: Which project does this suggestion apply to?
      options:
        - 'packages/sanity-plugin-nacelle-input'
        - 'packages/shopify-cart'
        - 'packages/shopify-checkout'
        - 'Something else'
      multiple: true
    validations:
      required: true
  - type: dropdown
    id: checked-issues
    attributes:
      label: Is this a new enhancement?
      description: Have you checked the [Issues](https://github.com/getnacelle/nacelle-js/issues?q=is%3Aissue+label%3Aenhancement) tab to see if this enhancement has already been suggested?
      options:
        - "I haven't checked the existing Issues, but I'll do that now."
        - "Yes - I've checked the existing Issues, and I'm reporting a new issue."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description & Motivation
      placeholder: Tell us about the enhancement you'd like to see, and why. Screenshots, gifs or videos are encouraged.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative approaches
      placeholder: Describe alternatives you've considered.
    validations:
      required: true
  - type: input
    id: link-to-example
    attributes:
      label: Link to Example
      description: If applicable, please provide a link to a [minimal example](https://stackoverflow.com/help/minimal-reproducible-example) of the enhancement, such as a [Code Sandbox](https://codesandbox.io) or [StackBlitz](https://stackblitz.com) project.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/getnacelle/nacelle-js/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
