name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ENG-6843/shopify-cart-1.0.0
    paths:
      - 'packages/**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            shopify-checkout:
              - 'packages/shopify-checkout/**'

      - name: Install Dependencies
        run: npm ci

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1.2.0
        with:
          commit: 'build: version packages'
          title: 'build: version packages'
          version: npm run version
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NACELLE_NPMJS_TOKEN }}

      - name: Shopify Checkout - npm run test:coverage
        if: steps.changes.outputs.shopify-checkout == 'true'
        run: npm run test:coverage
        working-directory: packages/shopify-checkout

      - name: Analyze with SonarCloud
        if: steps.changes.outputs.shopify-checkout == 'true'
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: packages/shopify-checkout
          args: >
            -Dsonar.organization=getnacelle
            -Dsonar.projectKey=getnacelle_nacelle-js_package_shopify_checkout
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sources=src
            -Dsonar.exclusions=src/**/*.test.ts
            -Dsonar.tests=src
            -Dsonar.test.inclusions=src/**/*.test.ts
